import { db } from '@/db';
import { agents } from '@/db/schema';

async function main() {
    const now = new Date();
    const ninetyDaysAgo = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);

    const getRandomDate = (start: Date, end: Date) => {
        return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
    };

    const getRandomInt = (min: number, max: number) => {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    };

    const getRandomRating = () => {
        return Math.round((3.5 + Math.random() * 1.5) * 10) / 10;
    };

    const featuredIndexes = [2, 5, 11, 15, 20];
    const trendingIndexes = [1, 8, 14, 18];
    const verifiedIndexes = [0, 3, 7, 12, 16, 21];

    const sampleAgents = [
        {
            name: 'ChatFlow AI',
            slug: 'chatflow-ai',
            description: 'Intelligent conversational AI platform that enables natural language interactions with your data. Features advanced context awareness and multi-turn conversations. Perfect for customer support automation and interactive chatbots.',
            categoryId: 1,
            features: 'Natural Language Processing, Context Awareness, Multi-turn Conversations, API Integration, Custom Training',
            websiteUrl: 'https://chatflow-ai.example.com',
            repoUrl: 'https://github.com/chatflow/chatflow-ai',
            demoUrl: 'https://demo.chatflow-ai.example.com',
            imageUrl: 'https://images.example.com/chatflow-ai.png',
            creatorName: 'Sarah Chen',
            status: 'approved',
            featured: verifiedIndexes.includes(0),
            trending: trendingIndexes.includes(0),
            verified: verifiedIndexes.includes(0),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'VoiceGen Pro',
            slug: 'voicegen-pro',
            description: 'State-of-the-art text-to-speech AI with realistic voice synthesis. Supports multiple languages and custom voice cloning. Ideal for content creators, podcasters, and accessibility applications.',
            categoryId: 1,
            features: 'Voice Cloning, Multi-language Support, Emotional Tone Control, Real-time Generation, High Fidelity Audio',
            websiteUrl: 'https://voicegen-pro.example.com',
            demoUrl: 'https://demo.voicegen-pro.example.com',
            imageUrl: 'https://images.example.com/voicegen-pro.png',
            creatorName: 'Michael Rodriguez',
            status: 'approved',
            featured: featuredIndexes.includes(1),
            trending: trendingIndexes.includes(1),
            verified: verifiedIndexes.includes(1),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'CodeAssist Pro',
            slug: 'codeassist-pro',
            description: 'Advanced AI-powered code completion and generation tool. Understands context and coding patterns to provide intelligent suggestions. Supports 20+ programming languages with framework-specific knowledge.',
            categoryId: 2,
            features: 'Intelligent Code Completion, Bug Detection, Code Refactoring, Documentation Generation, Multi-language Support',
            websiteUrl: 'https://codeassist-pro.example.com',
            repoUrl: 'https://github.com/codeassist/codeassist-pro',
            imageUrl: 'https://images.example.com/codeassist-pro.png',
            creatorName: 'David Park',
            status: 'approved',
            featured: featuredIndexes.includes(2),
            trending: trendingIndexes.includes(2),
            verified: verifiedIndexes.includes(2),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'BugHunter AI',
            slug: 'bughunter-ai',
            description: 'Automated code review and bug detection system powered by machine learning. Identifies security vulnerabilities, performance issues, and code smells. Integrates seamlessly with CI/CD pipelines.',
            categoryId: 2,
            features: 'Automated Code Review, Security Scanning, Performance Analysis, CI/CD Integration, Custom Rules',
            websiteUrl: 'https://bughunter-ai.example.com',
            repoUrl: 'https://github.com/bughunter/bughunter-ai',
            demoUrl: 'https://demo.bughunter-ai.example.com',
            creatorName: 'Jennifer Liu',
            status: 'approved',
            featured: featuredIndexes.includes(3),
            trending: trendingIndexes.includes(3),
            verified: verifiedIndexes.includes(3),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'DesignForge AI',
            slug: 'designforge-ai',
            description: 'AI-powered design assistant that generates professional graphics and layouts. Learns from your brand guidelines to maintain consistency. Creates everything from social media posts to marketing materials.',
            categoryId: 3,
            features: 'Brand Consistency, Template Generation, Multi-format Export, Collaboration Tools, Asset Library',
            websiteUrl: 'https://designforge-ai.example.com',
            imageUrl: 'https://images.example.com/designforge-ai.png',
            creatorName: 'Emma Thompson',
            status: 'approved',
            featured: featuredIndexes.includes(4),
            trending: trendingIndexes.includes(4),
            verified: verifiedIndexes.includes(4),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'ArtCanvas Studio',
            slug: 'artcanvas-studio',
            description: 'Creative AI platform for digital artists and illustrators. Generate unique artwork from text descriptions with fine-grained control over style and composition. Supports iterative refinement and style transfer.',
            categoryId: 3,
            features: 'Text-to-Image Generation, Style Transfer, Iterative Refinement, High Resolution Output, Custom Models',
            websiteUrl: 'https://artcanvas-studio.example.com',
            demoUrl: 'https://demo.artcanvas-studio.example.com',
            imageUrl: 'https://images.example.com/artcanvas-studio.png',
            creatorName: 'Alex Martinez',
            status: 'approved',
            featured: featuredIndexes.includes(5),
            trending: trendingIndexes.includes(5),
            verified: verifiedIndexes.includes(5),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'ContentCraft Writer',
            slug: 'contentcraft-writer',
            description: 'AI writing assistant for bloggers, marketers, and content creators. Generates SEO-optimized articles, product descriptions, and marketing copy. Maintains consistent brand voice across all content.',
            categoryId: 4,
            features: 'SEO Optimization, Tone Adjustment, Plagiarism Detection, Multi-format Writing, Content Calendar',
            websiteUrl: 'https://contentcraft-writer.example.com',
            repoUrl: 'https://github.com/contentcraft/writer',
            imageUrl: 'https://images.example.com/contentcraft-writer.png',
            creatorName: 'Rachel Green',
            status: 'approved',
            featured: featuredIndexes.includes(6),
            trending: trendingIndexes.includes(6),
            verified: verifiedIndexes.includes(6),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'ProofMaster AI',
            slug: 'proofmaster-ai',
            description: 'Advanced grammar and style checking powered by deep learning. Goes beyond basic spell-check to improve clarity, conciseness, and readability. Provides context-aware suggestions for professional writing.',
            categoryId: 4,
            features: 'Grammar Checking, Style Improvement, Readability Analysis, Citation Management, Plagiarism Check',
            websiteUrl: 'https://proofmaster-ai.example.com',
            demoUrl: 'https://demo.proofmaster-ai.example.com',
            creatorName: 'Thomas Anderson',
            status: 'approved',
            featured: featuredIndexes.includes(7),
            trending: trendingIndexes.includes(7),
            verified: verifiedIndexes.includes(7),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'DataViz Engine',
            slug: 'dataviz-engine',
            description: 'Transform complex datasets into beautiful, interactive visualizations automatically. AI understands your data patterns and recommends the most effective chart types. Supports real-time data streaming and custom dashboards.',
            categoryId: 5,
            features: 'Auto Chart Selection, Real-time Updates, Interactive Dashboards, Data Cleaning, Export Options',
            websiteUrl: 'https://dataviz-engine.example.com',
            repoUrl: 'https://github.com/dataviz/engine',
            demoUrl: 'https://demo.dataviz-engine.example.com',
            imageUrl: 'https://images.example.com/dataviz-engine.png',
            creatorName: 'Dr. Lisa Wang',
            status: 'approved',
            featured: featuredIndexes.includes(8),
            trending: trendingIndexes.includes(8),
            verified: verifiedIndexes.includes(8),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'PredictFlow Analytics',
            slug: 'predictflow-analytics',
            description: 'Predictive analytics platform that forecasts trends and identifies patterns in your data. Uses ensemble machine learning models for high accuracy predictions. Provides actionable insights for business decision-making.',
            categoryId: 5,
            features: 'Trend Forecasting, Pattern Recognition, Anomaly Detection, What-if Analysis, Model Explainability',
            websiteUrl: 'https://predictflow-analytics.example.com',
            imageUrl: 'https://images.example.com/predictflow-analytics.png',
            creatorName: 'James Mitchell',
            status: 'approved',
            featured: featuredIndexes.includes(9),
            trending: trendingIndexes.includes(9),
            verified: verifiedIndexes.includes(9),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'VideoEdit AI',
            slug: 'videoedit-ai',
            description: 'Automated video editing suite that cuts, arranges, and enhances footage intelligently. Detects highlights, removes silence, and adds transitions automatically. Perfect for content creators and social media managers.',
            categoryId: 6,
            features: 'Auto-editing, Highlight Detection, Subtitle Generation, Background Removal, Multi-platform Export',
            websiteUrl: 'https://videoedit-ai.example.com',
            demoUrl: 'https://demo.videoedit-ai.example.com',
            imageUrl: 'https://images.example.com/videoedit-ai.png',
            creatorName: 'Sofia Garcia',
            status: 'approved',
            featured: featuredIndexes.includes(10),
            trending: trendingIndexes.includes(10),
            verified: verifiedIndexes.includes(10),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'StreamOptimizer Pro',
            slug: 'streamoptimizer-pro',
            description: 'AI-powered video compression and optimization for streaming platforms. Maintains visual quality while reducing file size significantly. Supports adaptive bitrate streaming and multiple format conversions.',
            categoryId: 6,
            features: 'Smart Compression, Format Conversion, Quality Preservation, Batch Processing, CDN Integration',
            websiteUrl: 'https://streamoptimizer-pro.example.com',
            repoUrl: 'https://github.com/streamoptimizer/pro',
            creatorName: 'Kevin Patel',
            status: 'approved',
            featured: featuredIndexes.includes(11),
            trending: trendingIndexes.includes(11),
            verified: verifiedIndexes.includes(11),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'MelodyMaker AI',
            slug: 'melodymaker-ai',
            description: 'Create original music compositions with AI assistance. Generate melodies, harmonies, and full arrangements in various genres. Offers MIDI export and seamless DAW integration for further refinement.',
            categoryId: 7,
            features: 'Music Composition, Genre Flexibility, MIDI Export, DAW Integration, Stem Separation',
            websiteUrl: 'https://melodymaker-ai.example.com',
            demoUrl: 'https://demo.melodymaker-ai.example.com',
            imageUrl: 'https://images.example.com/melodymaker-ai.png',
            creatorName: 'Maya Johnson',
            status: 'approved',
            featured: featuredIndexes.includes(12),
            trending: trendingIndexes.includes(12),
            verified: verifiedIndexes.includes(12),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'AudioMaster Studio',
            slug: 'audiomaster-studio',
            description: 'Professional audio mastering and enhancement powered by machine learning. Automatically adjusts EQ, compression, and limiting for broadcast-ready sound. Learns from reference tracks to match your desired sonic profile.',
            categoryId: 7,
            features: 'Auto Mastering, Reference Matching, Noise Reduction, Vocal Enhancement, Batch Processing',
            websiteUrl: 'https://audiomaster-studio.example.com',
            repoUrl: 'https://github.com/audiomaster/studio',
            creatorName: 'Daniel Kim',
            status: 'approved',
            featured: featuredIndexes.includes(13),
            trending: trendingIndexes.includes(13),
            verified: verifiedIndexes.includes(13),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'LearnPath AI',
            slug: 'learnpath-ai',
            description: 'Personalized learning platform that adapts to each student\'s pace and style. Creates custom curricula based on learning goals and performance. Provides real-time feedback and intelligent tutoring assistance.',
            categoryId: 8,
            features: 'Adaptive Learning, Progress Tracking, Personalized Content, Interactive Exercises, Performance Analytics',
            websiteUrl: 'https://learnpath-ai.example.com',
            demoUrl: 'https://demo.learnpath-ai.example.com',
            imageUrl: 'https://images.example.com/learnpath-ai.png',
            creatorName: 'Dr. Patricia Brown',
            status: 'approved',
            featured: featuredIndexes.includes(14),
            trending: trendingIndexes.includes(14),
            verified: verifiedIndexes.includes(14),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'QuizGenius Pro',
            slug: 'quizgenius-pro',
            description: 'Automatically generate quizzes and assessments from any content source. Creates questions of varying difficulty levels with detailed explanations. Supports multiple question types and automatic grading.',
            categoryId: 8,
            features: 'Question Generation, Multiple Formats, Auto Grading, Difficulty Scaling, Analytics Dashboard',
            websiteUrl: 'https://quizgenius-pro.example.com',
            repoUrl: 'https://github.com/quizgenius/pro',
            creatorName: 'Amanda Foster',
            status: 'approved',
            featured: featuredIndexes.includes(15),
            trending: trendingIndexes.includes(15),
            verified: verifiedIndexes.includes(15),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'DocuScan AI',
            slug: 'docuscan-ai',
            description: 'Advanced OCR and document processing system with intelligent data extraction. Converts scanned documents and images into editable, searchable text. Handles multiple languages and complex layouts with high accuracy.',
            categoryId: 9,
            features: 'OCR Technology, Data Extraction, Multi-language Support, Layout Recognition, PDF Generation',
            websiteUrl: 'https://docuscan-ai.example.com',
            imageUrl: 'https://images.example.com/docuscan-ai.png',
            creatorName: 'Robert Taylor',
            status: 'approved',
            featured: featuredIndexes.includes(16),
            trending: trendingIndexes.includes(16),
            verified: verifiedIndexes.includes(16),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'TaskFlow Automation',
            slug: 'taskflow-automation',
            description: 'Intelligent workflow automation platform that connects apps and automates repetitive tasks. Uses AI to suggest optimal workflows and handle exceptions. Includes no-code builder and extensive integration library.',
            categoryId: 9,
            features: 'No-code Builder, Smart Triggers, Error Handling, Integration Hub, Workflow Templates',
            websiteUrl: 'https://taskflow-automation.example.com',
            demoUrl: 'https://demo.taskflow-automation.example.com',
            repoUrl: 'https://github.com/taskflow/automation',
            creatorName: 'Nicole Adams',
            status: 'approved',
            featured: featuredIndexes.includes(17),
            trending: trendingIndexes.includes(17),
            verified: verifiedIndexes.includes(17),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'SentimentPulse Analytics',
            slug: 'sentimentpulse-analytics',
            description: 'Real-time sentiment analysis for social media, customer reviews, and feedback. Tracks brand perception and identifies emerging trends. Provides actionable insights with customizable alerts and reporting.',
            categoryId: 10,
            features: 'Sentiment Analysis, Trend Detection, Multi-platform Monitoring, Custom Alerts, Reporting Dashboard',
            websiteUrl: 'https://sentimentpulse-analytics.example.com',
            imageUrl: 'https://images.example.com/sentimentpulse-analytics.png',
            creatorName: 'Christopher Lee',
            status: 'approved',
            featured: featuredIndexes.includes(18),
            trending: trendingIndexes.includes(18),
            verified: verifiedIndexes.includes(18),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'BrandWatch AI',
            slug: 'brandwatch-ai',
            description: 'Comprehensive brand monitoring and competitive intelligence platform. Tracks mentions across web, social media, and news sources. Uses NLP to understand context and identify opportunities or threats.',
            categoryId: 10,
            features: 'Brand Monitoring, Competitor Analysis, Media Coverage, Influencer Tracking, Crisis Detection',
            websiteUrl: 'https://brandwatch-ai.example.com',
            repoUrl: 'https://github.com/brandwatch/ai',
            demoUrl: 'https://demo.brandwatch-ai.example.com',
            creatorName: 'Stephanie Martinez',
            status: 'approved',
            featured: featuredIndexes.includes(19),
            trending: trendingIndexes.includes(19),
            verified: verifiedIndexes.includes(19),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'SEOBoost Engine',
            slug: 'seoboost-engine',
            description: 'AI-driven SEO optimization suite that analyzes and improves your website\'s search rankings. Provides keyword research, content optimization, and technical SEO recommendations. Tracks performance and competitor strategies.',
            categoryId: 11,
            features: 'Keyword Research, Content Optimization, Technical SEO, Rank Tracking, Competitor Analysis',
            websiteUrl: 'https://seoboost-engine.example.com',
            imageUrl: 'https://images.example.com/seoboost-engine.png',
            creatorName: 'Brandon Wong',
            status: 'approved',
            featured: featuredIndexes.includes(20),
            trending: trendingIndexes.includes(20),
            verified: verifiedIndexes.includes(20),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'AdOptimizer Pro',
            slug: 'adoptimizer-pro',
            description: 'Intelligent advertising campaign management across multiple platforms. Automatically adjusts bids, targeting, and creative elements for maximum ROI. Uses predictive analytics to allocate budget effectively.',
            categoryId: 11,
            features: 'Campaign Management, Bid Optimization, A/B Testing, ROI Tracking, Multi-platform Support',
            websiteUrl: 'https://adoptimizer-pro.example.com',
            demoUrl: 'https://demo.adoptimizer-pro.example.com',
            repoUrl: 'https://github.com/adoptimizer/pro',
            creatorName: 'Jessica Turner',
            status: 'approved',
            featured: featuredIndexes.includes(21),
            trending: trendingIndexes.includes(21),
            verified: verifiedIndexes.includes(21),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'TranslateMaster AI',
            slug: 'translatemaster-ai',
            description: 'Neural machine translation with context-aware accuracy for 100+ languages. Preserves formatting, tone, and cultural nuances. Offers real-time translation API and document processing capabilities.',
            categoryId: 12,
            features: 'Neural Translation, Context Awareness, Document Processing, API Access, Quality Assurance',
            websiteUrl: 'https://translatemaster-ai.example.com',
            imageUrl: 'https://images.example.com/translatemaster-ai.png',
            creatorName: 'Maria Santos',
            status: 'approved',
            featured: featuredIndexes.includes(22),
            trending: trendingIndexes.includes(22),
            verified: verifiedIndexes.includes(22),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
        {
            name: 'LinguaConnect Pro',
            slug: 'linguaconnect-pro',
            description: 'Comprehensive language learning platform with AI-powered conversation practice. Adapts to your proficiency level and learning style. Includes pronunciation coaching, vocabulary building, and cultural insights.',
            categoryId: 12,
            features: 'Conversation Practice, Pronunciation Coaching, Adaptive Lessons, Progress Tracking, Cultural Content',
            websiteUrl: 'https://linguaconnect-pro.example.com',
            repoUrl: 'https://github.com/linguaconnect/pro',
            demoUrl: 'https://demo.linguaconnect-pro.example.com',
            creatorName: 'Andrew Chen',
            status: 'approved',
            featured: featuredIndexes.includes(23),
            trending: trendingIndexes.includes(23),
            verified: verifiedIndexes.includes(23),
            averageRating: getRandomRating(),
            ratingsCount: getRandomInt(10, 100),
            upvotesCount: getRandomInt(50, 500),
            commentsCount: getRandomInt(5, 50),
            downloadsCount: getRandomInt(100, 5000),
            sharesCount: getRandomInt(10, 200),
            visitsCount: getRandomInt(500, 10000),
            createdBy: null,
            createdAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
            updatedAt: getRandomDate(ninetyDaysAgo, now).toISOString(),
        },
    ];

    await db.insert(agents).values(sampleAgents);
    
    console.log('✅ Agents seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});